version: '3'
services:
  odoo:
    image: odoo:13
    restart: always
    ports:
    - "8069:8069"
    links:
    - db
    volumes:
    - ./extra-addons:/mnt/extra-addons
  db:
    image: postgres:12
    restart: always
    environment:
    - POSTGRES_USER=odoo
    - POSTGRES_PASSWORD=odoo