version: '3'
services:
  odoo:
    image: odoo:13
    restart: always
    ports:
    - "8069:8069"
    #- "2222:22"
    links:
    - db
    volumes:
    - ./extra-addons:/mnt/extra-addons
    #environment:
    #- ODOO_USER=odoo
    #- ODOO_PASSWORD=odoo
  db:
    image: postgres:12
    restart: always
    environment:
    - POSTGRES_USER=odoo
    - POSTGRES_PASSWORD=odoo
    - POSTGRES_DB=postgres
    - PGDATA=/var/lib/postgresql/pgdata